### PR TITLE
It creates Guardfile from task dependencies

### LINKED ISSUE #45: It should read task dependencies automatically
It should read tasks from [Rake tasks variable](https://ruby.github.io/rake/Rake/Task.html#method-c-tasks) and watch which file changed and call the task that has it as a dependency.

When I run `rake -P` I get tasks and dependencies:

```
rake test
    test/teste1/teste1.pdf
rake test/teste1/teste1.pdf
    test/teste1/teste1.tex
```

We can then create a Guardfile with this content:

```ruby
guard 'rake', :task => 'test/teste1/teste1.pdf' do
  watch(%r{^test/teste1/teste1.tex$})
end
```

I have created a simple task file to generate this code:

```ruby
desc 'Update Guardfile from Rakefile tasks'
task :upguard do
  # https://ruby.github.io/rake/Rake/Task.html#method-c-tasks
  Rake::Task.tasks.each do |t|

    # ignore tasks that aren't files names
    next unless t.name.include? "/"

    # guard 'rake', :task => 'doit' do
    #   watch(%r{^some_files/.+$})
    # end

    puts "guard 'rake', :task => '#{t.name}' do"

    t.prerequisites.each do |p|
      puts "  watch(%r{^#{p}$})"
    end

    puts "end"

  end
end

```

Here's this `upguard` task execution:

```
$ rake -T
rake test     # gera os testes
rake upguard  # Update Guardfile from Rakefile tasks
$ rake -P
rake default
rake test
    test/teste1/teste1.pdf
rake test/teste1/teste1.pdf
    test/teste1/teste1.tex
rake upguard
$ rake upguard > Guardfile
$ cat Guardfile 
guard 'rake', :task => 'test/teste1/teste1.pdf' do
  watch(%r{^test/teste1/teste1.tex$})
end
```

I would like this `guard-rake` plugin to do it on the fly. When Rakefile changes it should load new watches.

### PR DESCRIPTION
**Pull request by edusantana**
I had to create a new PR, but here's the code with the README updated.

closes #45

### CODE REVIEW

**Comment by edusantana** [comment]
@rubyist thank you for this plugin.

**Comment by edusantana** [comment]
@rubyist can you take a look on this pull request? I would love to use this.

**Comment by rubyist** [comment]
Thanks!

**Comment by edusantana** [comment]
@rubyist can you publish a new release?

**Comment by edusantana** [comment]
@rubyist can you publish a new Release with this code?

**Comment by edusantana** [comment]
The [current release](https://rubygems.org/gems/guard-rake) is still `1.0.0`.

**Pull request merged**
